- type: startingGear
  id: ChronoLegioneerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRecruitNT
    back: ClothingBackpackStasisBatteryUnremoveableFilled
    mask: ClothingMaskGasChronoUnremoveable
    eyes: ClothingEyesHudChronoUnremoveable
    ears: ClothingHeadsetChronolegioneerUnremoveable
    gloves: ClothingHandsGlovesChronoLegioneerUnremoveable
    outerClothing: ClothingOuterHardsuitChronolegioneerUnremoveable
    suitstorage: JetpackChronoUnremoveable
    shoes: ClothingShoesBootsChronoUnremoveable
    id: ChronoPDA
    belt: WeaponStasisGun
    pocket1: PinpointerStation
    pocket2: SonicScrewdriver
  innerClothingSkirt: ClothingUniformJumpskirtColorBlack

- type: startingGear
  id: SithGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSith
    mask: ClothingMaskGasSith
    neck: ClothingNeckCloakSith
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesSith
    shoes: ClothingShoesSith
    id: AgentIDCard
    back: JetpackBlackFilled
    ears: ClothingHeadsetGrey
    pocket1: LightsaberDoubleRed
    pocket2: PinpointerUniversal
    belt: ClothingBeltSith

- type: startingGear
  id: KyloGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitKylo
    mask: ClothingMaskGasSyndicate
    neck: ClothingNeckCloakKylo
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesSith
    id: AgentIDCard
    back: JetpackBlackFilled
    ears: ClothingHeadsetGrey
    pocket1: LightsaberCrossguardRed
    pocket2: PinpointerUniversal
    belt: ClothingBeltSith
