- type: entity
  id: PrisonStation
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationNanotrasen
    - BaseStationAlertLevels
  noSpawn: true
  components:
    - type: Transform
