using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Partners.UI;

[GenerateTypedNameReferences]
public sealed partial class SpecialRolesMenu : FancyWindow
{
    [Dependency] private readonly IClientConsoleHost _conHost = default!;

    private readonly SpecialRolesEui _eui;
    public SpecialRolesMenu(SpecialRolesEui eui)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _eui = eui;

        Request.OnPressed += (_) =>
        {
            var cmd = $"pickspecialrole {_eui.CurrentRole}";

            _conHost.ExecuteCommand(cmd);
        };

        RoleSelectButton.OnItemSelected += (args) =>
        {
            var metadata = RoleSelectButton.GetItemMetadata(args.Id);
            if (metadata is string cast)
            {
                _eui.SelectRole(cast);
                args.Button.SelectId(args.Id);
            }
        };
    }
}

