- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesBarratry
  - StoriesBagel
  - StoriesBox
  - StoriesCore
  - StoriesFland
  - StoriesMarathon
  - StoriesMeta
  - StoriesOasis
  - StoriesOmega
  - StoriesPacked
  - StoriesTrain
  - StoriesCog
  - CorvaxAstra
  - CorvaxAvrite
  - CorvaxDelta
  - CorvaxSilly
  # - CorvaxTerra
  - CorvaxPilgrim
  # - CorvaxPearl
  - CorvaxPaper
  # - CorvaxOutpost
  # - CorvaxMaus
  # - CorvaxIshimura
  # - CorvaxFrame
