- type: gameMapPool
  id: StoriesDefaultMapPool
  maps:
  - StoriesAtlas
  - StoriesBagel
  - StoriesBox
  - StoriesCluster
  - StoriesCore
  - StoriesFland
  - StoriesMarathon
  - StoriesMeta
  - StoriesOasis
  - StoriesOmega
  - StoriesOrigin
  - StoriesPacked
  - StoriesSaltern
  - StoriesTrain
