- type: job
  id: HeadOfSpacePrison
  name: job-name-hosp
  description: job-description-hosp
  playTimeTracker: JobHeadOfSpacePrison
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: SpacePrison
      time: 36000 # 10 hours
  weight: 10
  startingGear: HeadOfSpacePrisonGear
  icon: "JobIconHeadOfSpacePrison"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  - Brig
  - Security
  - Armory
  - Maintenance
  - Service
  - External
  - Detective
  - Engineering
  - Atmospherics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: HeadOfSpacePrisonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSP
    back: ClothingBackpackSpacePrisonFilled
    shoes: ClothingShoesBootsJackSP
    outerClothing: ClothingOuterCoatHoSP
    eyes: ClothingEyesGlassesSpacePrison
    id: HeadOfSPPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetPrisonAlt
    belt: ClothingBeltHoSPSheathFilled
    pocket1: WeaponPistolMk58
  innerclothingskirt: ClothingUniformJumpskirtHoSP
  satchel: ClothingBackpackSatchelSpacePrisonFilled
  duffelbag: ClothingBackpackDuffelSpacePrisonFilled
