- type: job
  id: PRISONPrisoner
  name: заключенный космической тюрьмы
  playTimeTracker: JobPrisoner
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 часа
  description: Как я сюда попал?
  startingGear: PRISONPrisoner
  icon: "JobIconPRISONPrisoner"
  supervisors: job-supervisors-everyone
  canBeAntag: false
  access:
  - Prisoner
  special:
  - !type:AddComponentSpecial
    components:
    - type: Prisoner

- type: startingGear
  id: PRISONPrisoner
  equipment:
    id: PRISONIDCardPrisoner
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
