- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs # Stories-RoleTime
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  # Stories skills - start
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills
        skills:
          Shuttle: 1.0
  # Stories skills - end

- type: startingGear
  id: CargoTechGear
  equipment:
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff
