- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: бумажный принтер (машинная плата)
  description: Печатна плата для бумажного принтера.
  components:
  - type: MachineBoard
    prototype: PrinterDoc
    stackRequirements:
      MatterBin: 3
      Manipulator: 1
      Glass: 1

- type: entity
  id: ReflectorBoxMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Отражатель, тип "Коробка"
  description: Машинная плата отражателя, тип "Коробка"
  components:
  - type: Sprite
    sprite: _Stories/Objects/Misc/module.rsi
    state: reflectorbox_circuitboard
  - type: MachineBoard
    prototype: ReflectorBox
    stackRequirements:
      Capacitor: 3
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 1
        defaultPrototype: PowerCellMedium

- type: entity
  id: ReflectorCornerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Отражатель, тип "Угловой"
  description: Машинная плата отражателя, тип "Угловой"
  components:
  - type: Sprite
    sprite: _Stories/Objects/Misc/module.rsi
    state: reflectorcorner_circuitboard
  - type: MachineBoard
    prototype: ReflectorCorner
    stackRequirements:
      Capacitor: 3
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 1
        defaultPrototype: PowerCellMedium

- type: entity
  id: ReflectorCornerTsideMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: Отражатель, тип "Двойной-Угловой"
  description: Машинная плата отражателя, тип "Двойной-Угловой"
  components:
  - type: Sprite
    sprite: _Stories/Objects/Misc/module.rsi
    state: reflectortsidecorner_circuitboard
  - type: MachineBoard
    prototype: ReflectorCornerTside
    stackRequirements:
      Capacitor: 3
      CableHV: 10
    componentRequirements:
      PowerCell:
        amount: 1
        defaultPrototype: PowerCellMedium

