- type: job
  id: Botanist
  name: job-name-botanist
  description: job-description-botanist
  playTimeTracker: JobBotanist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs # Stories-RoleTime
  startingGear: BotanistGear
  icon: "JobIconBotanist"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Hydroponics
  extendedAccess:
  - Kitchen
  - Bar
  # Stories skills - start
  special:
  - !type:AddComponentSpecial
    components:
      - type: Skills
        skills:
          Melee: 0.1
  # Stories skills - end

- type: startingGear
  id: BotanistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: BotanistPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltPlantFilled
  #storage:
    #back:
    #- Stuff
