- type: job
  id: PRISONHeadOfPrison
  name: начальник космической тюрьмы
  description: Охраняйте это место используя все возможное и невозможно, иначе на свободу вырвутся самые опасные обитатели вселенной.
  playTimeTracker: JobHeadOfSpacePrison
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Prison
      time: 18000 # 5 hours
  weight: 10
  startingGear: PRISONHeadOfPrisonGear
  icon: "JobIconHeadOfSpacePrison"
  requireAdminNotify: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
  - HeadOfPrison
  - PrisonBrig
  - Prison
  - PrisonMed
  - PrisonEng
  - Prisoner
  - Command
  - Brig
  - Security
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: Skills
        skills:
          Medicine: 0.3
          Melee: 0.9
          Guns: 1.0
          EnergyGuns: 1.0
          Shuttle: 1.0

- type: startingGear
  id: PRISONHeadOfPrisonGear
  storage:
    back:
    - WeaponPistolMk58
    - Flash
    - MagazinePistol
  equipment:
    jumpsuit: PRISONClothingUniformJumpsuitHeadOfPrison
    id: PRISONPDAHeadOfPrison
    ears: PRISONClothingHeadsetAlt
    outerClothing: PRISONClothingOuterCoatHeadOfPrison
    eyes: PRISONClothingEyesGlasses
    belt: PRISONClothingBeltSheathFilled

