- type: entity
  id: CrateServicePrinter
  parent: CrateGenericSteel
  name: коробка с принтером
  description: Принтер для всяких бюрократических штучек.
  components:
  - type: StorageFill
    contents:
    - id: BoxPrinter
